### PR TITLE
made a start on a markdown editor

### PR DESCRIPTION
**Pull request by jamessessford**
Hey Steve,

I had some free time this afternoon so had a look at working on the markdown for the articles. It definitely isn't ready to merge in yet but wanted to create somewhere it could be discussed/let you have a look at the direction I was going with it,

Cheers!

### CODE REVIEW

**Comment by JustSteveKing** [comment]
Fantastic @jamessessford - been meaning to get back on this, but been crazy busy with getting the latest work release ready and got carried away with youtube stuff!

**Comment by jamessessford** [comment]
No problem @JustSteveKing - I've had a few of those weeks in a row at the real job!

I'll hopefully get a bit more time over the next few days to get this finished as a reusable component

**Comment by jamessessford** [comment]
Had a little bit of time this morning @JustSteveKing!

I've seperated the markdown editor into it's own component so it can be reused and left a comment in the create-article template to use the component for the summary as well

**Comment by JustSteveKing** [comment]
Fantastic! All I need to do now is add syntax highlighting, fix the preview screen to stop overlap - and it will be perfect!

**Comment by jamessessford** [comment]
Awesome!

I'm happy to explore that over the next couple of days if I get any free time bud?

**Comment by JustSteveKing** [comment]
@jamessessford that would be awesome! I am planning on streaming some PHPOnline stuff next week anyway

**Pull request merged**
