### PR TITLE
Syntax highlight

### PR DESCRIPTION
**Pull request by jamessessford**
Morning @JustSteveKing,

I had a bit of time to look at the syntax highlighting/making the editor a bit snappier last night/this morning.

I've brought in the Spatie Common Mark highlight package and pass the content through that before displaying.

Please give it a look over when you have a chance, any and all feedback welcome!

### CODE REVIEW

**Comment by JustSteveKing** [comment]
@jamessessford this works pretty well! The styling is a little off but the functionality is spot on!

**Comment by jamessessford** [comment]
Awesome! Cheers @JustSteveKing 

What are you thinking in terms of styling? I'm very happy to have a look but I'm not as good with CSS as PHP!

**Comment by JustSteveKing** [comment]
@jamessessford I wouldn't worry too much - something that can be polished while in the wild! The important part is getting the feature working, articles going through the approval process - then I can finish off the user dashboard and we can deploy it at long last!

**Comment by jamessessford** [comment]
Definitely @JustSteveKing  - pretty excited to see this live!

Do you want me to mark this as ready to review so it can be pulled in and if I have any free time over the weekend/next week I can see if I can give you a hand with some of the other tasks?

**Comment by JustSteveKing** [comment]
@jamessessford yes please as and when you are ready! I will then run shift workbench against it!

I will spend some time this weekend getting aplan in place for features and getting this live!

**Comment by jamessessford** [comment]
Hey @JustSteveKing - I've convered this to a draft again while I'm working on a much better syntax highlighting integration!

**Comment by jamessessford** [comment]
Couldn't get the highlighting bug out of my head @JustSteveKing - I've just pushed another commit up with much better syntax highlighting if you'd like to give it a check over,

Cheers

**Pull request merged**
